POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "m",
    "password": "123"
}
###
POST http://localhost:8000/user/register/user HTTP/1.1
Content-Type: application/json

{
    "username": "s",
    "password": "123",
    "password2": "123",
    "phone": "1234567890"
}

###
POST http://localhost:8000/user/register/restaurant HTTP/1.1
Content-Type: application/json

{
    "username": "r",
    "password": "123",
    "password2": "123",
    "phone": 33,
    "location":"Aleppo"
}

###
POST http://localhost:8000/user/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "emp1",
    "password": "StrongPassword1263!"
}
###
POST http://localhost:8000/user/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "m",
    "password": "123"
}

###
GET http://localhost:8000/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4NTQ2NDk3LCJpYXQiOjE3NTg1NDYxOTcsImp0aSI6ImMwNDY5NWFlZTIwNTQ3NmI5OTdiOTYyYjRhZDAxMTgxIiwidXNlcl9pZCI6IjQifQ.Fd5uWDQ_1rJk91SrMAWo9Dcqoi7zo1x62mfKnDnLAdA

###
PUT http://localhost:8000/user/trusted/4/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4Njc0NDI5LCJpYXQiOjE3NTg2NzQxMjksImp0aSI6ImVlNGNhN2U4MDg2YzRmNDg5NTljNWFkZTM1ODk2NjdhIiwidXNlcl9pZCI6IjEifQ.QWhNIlNlVQsD94rYActEmGriYHEghkHfuOkkjBufxHc


###
PUT http://localhost:8000/user/evaluator_promote/4/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4NjczMTE1LCJpYXQiOjE3NTg2NzI4MTUsImp0aSI6ImM3ZDdjZTBjMDUxNzQ1NDZhMmY2YmQ1YmE1NWM2ZTkxIiwidXNlcl9pZCI6IjEifQ.RLwPsoi53sr2UuIsEvoNkYBG2WdCoxl3Ouj5EipFI6w

###
GET http://localhost:8000/user/?phone__gt=234 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4NzY0NDU4LCJpYXQiOjE3NTg3NjQxNTgsImp0aSI6Ijc4OGU3MjNmNGVmZjQ5YWY5MWZiNGU2MWU0NzZhMTk5IiwidXNlcl9pZCI6IjEifQ.BLrm4v8RPdHZHYiDRQHcmaHxfHPfXXHjoMcpm2WjwcM