# Generated by Django 5.2.6 on 2025-09-23 23:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queue', 'Queue'), ('processing', 'Processing'), ('finish', 'Finish')], max_length=30)),
                ('created_at', models.DateField()),
                ('expiry_date', models.DateField()),
                ('note', models.TextField(null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('accept', 'Accept'), ('reject', 'Reject')], default='processing', max_length=10)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_approved', to='restaurant.donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation_approved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
