# Generated by Django 5.2.6 on 2025-09-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('queue', 'Queue'), ('processing', 'Processing'), ('finish', 'Finish')], default='queue', max_length=30),
        ),
    ]
