# Generated by Django 5.2.6 on 2025-09-18 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_donation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='restaurant.restaurant'),
        ),
        migrations.CreateModel(
            name='DonationApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Accepted', 'Ac'), ('Pending', 'Pd'), ('Rejected', 'Rj')], default='Pending', max_length=10)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation_approved', to='restaurant.donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation_approved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
