# Generated by Django 5.2.6 on 2025-09-25 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_donation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='restaurant',
            new_name='user',
        ),
    ]
