# Generated by Django 5.2.6 on 2025-09-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_city_alter_user_role_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('evaluator', 'Evaluator'), ('supervisor', 'Supervisor'), ('admin', 'Admin'), ('restaurant', 'Restaurant')], max_length=20),
        ),
    ]
