# Generated by Django 5.2.6 on 2025-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_location_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
    ]
