# Generated by Django 5.2.6 on 2025-09-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_trusted'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('aleppo', 'Aleppo'), ('damascus', 'Damascus')], max_length=50)),
            ],
        ),
    ]
